version: "3.8"
services:
  raft1:
    build: ./strong
    command: [
      "go run main.go",
      "-id=1",
      "-peers=http://raft2:8002,http://raft3:8003"
    ]
    environment: ["NODE_ID=1","RAFT_BIND=127.0.0.1:12001","HTTP_BIND=0.0.0.0:8001","PEERS=127.0.0.1:12002,127.0.0.1:12003"]
    ports: ["8001:8001"]
  raft2:
    build: ./strong
    command: [
      "go run main.go",
      "-id=2",
      "-peers=http://raft1:8001,http://raft3:8003"
    ]
    environment: ["NODE_ID=2","RAFT_BIND=127.0.0.1:12002","HTTP_BIND=0.0.0.0:8002","PEERS=127.0.0.1:12001,127.0.0.1:12003"]
    ports: ["8002:8002"]
  raft3:
    build: ./strong
    command: [
      "go run main.go",
      "-id=3",
      "-peers=http://raft2:8002,http://raft1:8001"
    ]
    environment: ["NODE_ID=3","RAFT_BIND=127.0.0.1:12003","HTTP_BIND=0.0.0.0:8003","PEERS=127.0.0.1:12001,127.0.0.1:12002"]
    ports: ["8003:8003"]

  eventual1:
    build: ./eventual
    environment: ["NODE_ID=1","HTTP_BIND=0.0.0.0:9001","PEERS=127.0.0.1:9002,127.0.0.1:9003"]
    ports: ["9001:9001"]
  eventual2:
    build: ./eventual
    environment: ["NODE_ID=2","HTTP_BIND=0.0.0.0:9002","PEERS=127.0.0.1:9001,127.0.0.1:9003"]
    ports: ["9002:9002"]
  eventual3:
    build: ./eventual
    environment: ["NODE_ID=3","HTTP_BIND=0.0.0.0:9003","PEERS=127.0.0.1:9001,127.0.0.1:9002"]
    ports: ["9003:9003"]